### ISSUE TITLE
MTD TL not rendering within website

### ISSUE THREAD

**Issue by Ry3yr** [YalePrivacyLab/mastodon-timeline-widget#1]
Despite (hopefully?) being correctly embeded in the "head" and "body" sections, the tl code generated for MTD seems not to render properly
(The sample on the website at step 4 works fine tho :)  )

https://ry3yr.github.io/OSTR/Diarykeepers_Homepage/About.html

Feel free to make suggestions on where I went wrong.

-Ry3yr

PS: I did try the "purist" approach by creating a new fresh html file, and then implemementing approp. but that didn't work either -sadly

PPS: I'm starting to suspect I need to call jquery.

(However I now consider this issue "low priority" as rss also allows easy feed embeding:
https://codepen.io/daviddarnes/pen/VGaLoX )

**Comment by idotj** [comment]
@Ry3yr not sure if the widget gets maintained, but I can point you an alternative that I have being working on (without jQuery)
Here you have the url:
https://gitlab.com/idotj/mastodon-embed-feed-timeline

**Comment by Ry3yr** [comment]
Ah.
Perfect. Thanks :)


Am Sonntag, 22. Januar 2023 schrieb idotj ***@***.***>:
